=== scottnath/jsonresume-theme-microdata/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "link to the version of the schema that can validate the resume",
      "format": "uri"
    },
    "basics": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string",
          "description": "e.g. Web Developer"
        },
        "image": {
          "type": "string",
          "description": "URL (as per RFC 3986) to a image in JPEG or PNG format"
        },
        "email": {
          "type": "string",
          "description": "e.g. thomas@gmail.com",
          "format": "email"
        },
        "phone": {
          "type": "string",
          "description": "Phone numbers are stored as strings so use any format you like, e.g. 712-117-2923"
        },
        "pronouns": {
          "type": "string",
          "description": "e.g. they/them/theirs"
        },
        "url": {
          "type": "string",
          "description": "URL (as per RFC 3986) to your website, e.g. personal homepage",
          "format": "uri"
        },
        "summary": {
          "type": "string",
          "description": "Write a short 2-3 sentence biography about yourself"
        },
        "location": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "address": {
              "type": "string",
              "description": "To add multiple address lines, use \n. For example, 1234 Glücklichkeit Straße\nHinterhaus 5. Etage li."
            },
            "postalCode": {
              "type": "string"
            },
            "city": {
              "type": "string"
            },
            "countryCode": {
              "type": "string",
              "description": "code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN"
            },
            "region": {
              "type": "string",
              "description": "The general region where you live. Can be a US state, or a province, for instance."
            }
          }
        },
        "profiles": {
          "type": "array",
          "description": "Specify any number of social networks that you participate in",
          "additionalItems": false,
          "items": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
              "network": {
                "type": "string",
                "description": "e.g. Facebook or Twitter"
              },
              "username": {
                "type": "string",
                "description": "e.g. neutralthoughts"
              },
              "url": {
                "type": "string",
                "description": "e.g. http://twitter.example.com/neutralthoughts",
                "format": "uri"
              }
            }
          }
        }
      }
    },
    "work": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Facebook"
          },
          "itemtype": {
            "type": "string",
            "description": "Organization Schema.org vocabulary Type, e.g. `Corporation`"
          },
          "location": {
            "type": "string",
            "description": "e.g. Menlo Park, CA"
          },
          "description": {
            "type": "string",
            "description": "e.g. Social Media Company"
          },
          "position": {
            "type": "string",
            "description": "e.g. Software Engineer"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://facebook.example.com",
            "format": "uri"
          },
          "startDate": {
            "$ref": "#/$defs/iso8601"
          },
          "endDate": {
            "$ref": "#/$defs/iso8601"
          },
          "summary": {
            "type": "string",
            "description": "Give an overview of your responsibilities at the company"
          },
          "highlights": {
            "type": "array",
            "description": "Specify multiple accomplishments",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising"
            }
          }
        }
      }
    },
    "volunteer": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "organization": {
            "type": "string",
            "description": "e.g. Facebook"
          },
          "itemtype": {
            "type": "string",
            "description": "Organization Schema.org vocabulary Type, e.g. `NGO`"
          },
          "position": {
            "type": "string",
            "description": "e.g. Software Engineer"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://facebook.example.com",
            "format": "uri"
          },
          "startDate": {
            "$ref": "#/$defs/iso8601"
          },
          "endDate": {
            "$ref": "#/$defs/iso8601"
          },
          "summary": {
            "type": "string",
            "description": "Give an overview of your responsibilities at the company"
          },
          "highlights": {
            "type": "array",
            "description": "Specify accomplishments and achievements",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising"
            }
          }
        }
      }
    },
    "education": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "institution": {
            "type": "string",
            "description": "e.g. Massachusetts Institute of Technology"
          },
          "itemtype": {
            "type": "string",
            "description": "Organization Schema.org vocabulary Type, e.g. `EducationalOrganization`"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://facebook.example.com",
            "format": "uri"
          },
          "area": {
            "type": "string",
            "description": "e.g. Arts"
          },
          "studyType": {
            "type": "string",
            "description": "e.g. Bachelor"
          },
          "startDate": {
            "$ref": "#/$defs/iso8601"
          },
          "endDate": {
            "$ref": "#/$defs/iso8601"
          },
          "score": {
            "type": "string",
            "description": "grade point average, e.g. 3.67/4.0"
          },
          "courses": {
            "type": "array",
            "description": "List notable courses/subjects",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. H1302 - Introduction to American history"
            }
          }
        }
      }
    },
    "awards": {
      "type": "array",
      "description": "Specify any awards you have received throughout your professional career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "title": {
            "type": "string",
            "description": "e.g. One of the 100 greatest minds of the century"
          },
          "date": {
            "$ref": "#/$defs/iso8601"
          },
          "awarder": {
            "type": "string",
            "description": "e.g. Time Magazine"
          },
          "summary": {
            "type": "string",
            "description": "e.g. Received for my work with Quantum Physics"
          }
        }
      }
    },
    "certificates": {
      "type": "array",
      "description": "Specify any certificates you have received throughout your professional career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Certified Kubernetes Administrator"
          },
          "date": {
            "type": "string",
            "description": "e.g. 1989-06-12",
            "format": "date"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://example.com",
            "format": "uri"
          },
          "issuer": {
            "type": "string",
            "description": "e.g. CNCF"
          },
          "itemtype": {
            "type": "string",
            "description": "Organization Schema.org vocabulary Type for `issuer`, e.g. `EducationalOrganization`"
          }
        }
      }
    },
    "publications": {
      "type": "array",
      "description": "Specify your publications through your career",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. The World Wide Web"
          },
          "itemtype": {
            "type": "string",
            "description": "CreativeWork Schema.org vocabulary Type, e.g. `HowTo`"
          },
          "publisher": {
            "type": "string",
            "description": "e.g. IEEE, Computer Magazine"
          },
          "publisherItemtype": {
            "type": "string",
            "description": "Organization Schema.org vocabulary Type, e.g. `OnlineBusiness`"
          },
          "releaseDate": {
            "$ref": "#/$defs/iso8601"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://www.computer.org.example.com/csdl/mags/co/1996/10/rx069-abs.html",
            "format": "uri"
          },
          "summary": {
            "type": "string",
            "description": "Short summary of publication. e.g. Discussion of the World Wide Web, HTTP, HTML."
          }
        }
      }
    },
    "skills": {
      "type": "array",
      "description": "List out your professional skill-set",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Web Development"
          },
          "level": {
            "type": "string",
            "description": "e.g. Master"
          },
          "itemtype": {
            "type": "string",
            "description": "Schema.org vocabulary Type, e.g. `ComputerLanguage`"
          },
          "keywords": {
            "type": "array",
            "description": "List some keywords pertaining to this skill",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. HTML"
            }
          }
        }
      }
    },
    "languages": {
      "type": "array",
      "description": "List any other languages you speak",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "language": {
            "type": "string",
            "description": "e.g. English, Spanish"
          },
          "fluency": {
            "type": "string",
            "description": "e.g. Fluent, Beginner"
          }
        }
      }
    },
    "interests": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Philosophy"
          },
          "itemtype": {
            "type": "string",
            "description": "Thing Schema.org vocabulary Type, e.g. `Brand`"
          },
          "keywords": {
            "type": "array",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Friedrich Nietzsche"
            }
          }
        }
      }
    },
    "references": {
      "type": "array",
      "description": "List references you have received",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Timothy Cook"
          },
          "reference": {
            "type": "string",
            "description": "e.g. Joe blogs was a great employee, who turned up to work at least once a week. He exceeded my expectations when it came to doing nothing."
          }
        }
      }
    },
    "projects": {
      "type": "array",
      "description": "Specify career projects",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. The World Wide Web"
          },
          "itemtype": {
            "type": "string",
            "description": "Project Schema.org vocabulary Type, e.g. any `Organization`"
          },
          "description": {
            "type": "string",
            "description": "Short summary of project. e.g. Collated works of 2017."
          },
          "highlights": {
            "type": "array",
            "description": "Specify multiple features",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Directs you close but not quite there"
            }
          },
          "keywords": {
            "type": "array",
            "description": "Specify special elements involved",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. AngularJS"
            }
          },
          "startDate": {
            "$ref": "#/$defs/iso8601"
          },
          "endDate": {
            "$ref": "#/$defs/iso8601"
          },
          "url": {
            "type": "string",
            "format": "uri",
            "description": "e.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html"
          },
          "roles": {
            "type": "array",
            "description": "Specify your role on this project or in company",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Team Lead, Speaker, Writer"
            }
          },
          "entity": {
            "type": "string",
            "description": "Specify the relevant company/entity affiliations e.g. 'greenpeace', 'corporationXYZ'"
          },
          "entityItemtype": {
            "type": "string",
            "description": "Organization Schema.org vocabulary Type, e.g. `NGO`"
          },
          "type": {
            "type": "string",
            "description": " e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'"
          }
        }
      }
    },
    "meta": {
      "type": "object",
      "description": "The schema version and any other tooling configuration lives here",
      "additionalProperties": true,
      "properties": {
        "canonical": {
          "type": "string",
          "description": "URL (as per RFC 3986) to latest version of this document",
          "format": "uri"
        },
        "version": {
          "type": "string",
          "description": "A version field which follows semver - e.g. v1.0.0"
        },
        "lastModified": {
          "type": "string",
          "description": "Using ISO 8601 with YYYY-MM-DDThh:mm:ss"
        },
        "sectionTitles": {
          "type": "object",
          "description": "The title text used in each section's heading",
          "default": {
            "basics": "Basics",
            "work": "Work",
            "volunteer": "Volunteer",
            "education": "Education",
            "awards": "Awards",
            "certificates": "Certificates",
            "publications": "Publications",
            "skills": "Skills",
            "languages": "Languages",
            "interests": "Interests",
            "references": "References",
            "projects": "Projects",
            "meta": "meta"
          }
        }
      }
    }
  },
  "title": "Resume Schema",
  "type": "object",
  "$defs": {
    "iso8601": {
      "type": "string",
      "description": "e.g. 2014-06-29",
      "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"
    }
  }
}

=== scottnath/jsonresume-theme-microdata/sample.resume.json
{
  "certificates": [
    {
      "url": "https://www.linkedin.com/learning/python-essential-training-18764650/getting-started-with-python",
      "name": "Python Essential Training",
      "date": "2023-12-14",
      "issuer": "LinkedIn Learning"
    },
    {
      "url": "https://www.linkedin.com/learning/python-essential-training-18764650/getting-started-with-python",
      "name": "Python Essential Training II",
      "date": "2023-12-31",
      "issuer": "LinkedIn Learning"
    }
  ],
  "basics": {
    "profiles": [
      {
        "url": "https://mastodon.social/@scottnath",
        "username": "scottnath@mastodon.social",
        "network": "Mastodon"
      },
      {
        "url": "https://dev.to/scottnath",
        "username": "scottnath",
        "network": "DEV"
      },
      {
        "url": "https://github.com/scottnath",
        "username": "scottnath",
        "network": "GitHub"
      },
      {
        "url": "https://linkedin.com/in/scottnath",
        "username": "scottnath",
        "network": "LinkedIn"
      }
    ],
    "summary": "Scott Nath is a senior web developer and actor living in New York State with extensive experience creating full-stack apps and design systems.",
    "phone": "(212) 555-1212",
    "location": {
      "postalCode": "10001",
      "city": "New York",
      "countryCode": "US",
      "region": "NYC"
    },
    "name": "Scott Nath",
    "label": "Open Source Developer",
    "url": "https://scottnath.com",
    "email": "jsonresume@scottnath.com",
    "pronouns": "he/him",
    "image": "https://scottnath.com/scott-nath-profile-photo.avif"
  },
  "education": [
    {
      "studyType": "Bachelor",
      "area": "Theatre major",
      "startDate": "1990-09-01",
      "endDate": "1994-12-15",
      "url": "https://www.music.iastate.edu/theatre",
      "institution": "Iowa State University"
    },
    {
      "studyType": "Life",
      "area": "Knocks",
      "startDate": "2019-12-31",
      "endDate": "2021-01-01",
      "institution": "School of Hard Things"
    }
  ],
  "publications": [
    {
      "summary": "Step-by-step guide to create sturdy, portable stand-up controllers for video games using an X-Arcade Dual Joystick Controller and an adult-sized aluminum walker.",
      "name": "Stand Up Arcade Controllers Using Adult Walkers",
      "releaseDate": "2015-01-25",
      "url": "https://www.instructables.com/Stand-Up-Arcade-Controllers-using-Adult-Walkers/",
      "publisher": "Instrucables"
    },
    {
      "summary": "Step-by-step guide with linked source code to create a wi-fi streaming camera using a Raspberry Pi",
      "name": "Runnerpi: a Wifi-streaming POV Camera",
      "releaseDate": "2015-06-06",
      "url": "https://www.instructables.com/Runnerpi-a-wifi-streaming-POV-camera/",
      "publisher": "Instrucables"
    }
  ],
  "interests": [
    {
      "name": "Gardening",
      "keywords": ["kale", "flowers", "compost"]
    },
    {
      "name": "Meows",
      "keywords": ["Cats", "prrr", "tiny little angels"]
    }
  ],
  "awards": [
    {
      "title": "The Meowiest of Meowville",
      "summary": "For the one who is definitely the meowiest in all of Meowville - otherwise known as Purrtown ACK!",
      "date": "2024-04-29",
      "awarder": "Meowville"
    },
    {
      "title": "Coolest Meow",
      "summary": "Cool meows are common, but the coolest? THIS ONE",
      "date": "2024-04-30",
      "awarder": "Coolville"
    }
  ],
  "skills": [
    {
      "level": "Senior",
      "name": "Languages",
      "itemtype": "ComputerLanguage",
      "keywords": ["Javascript", "Typescript", "CSS", "HTML", "Bash/Shell", "Gherkin", "Python", "PHP"]
    },
    {
      "level": "Senior",
      "name": "Testing & QA",
      "itemtype": "SoftwareSourceCode",
      "keywords": [
        "accessibility",
        "UI Unit Testing",
        "Testing-Library",
        "Jest",
        "Playwright",
        "Vitest",
        "Chromatic",
        "Test driven development (TDD)",
        "Screen reader testing"
      ]
    },
    {
      "level": "Senior",
      "name": "DevOps",
      "itemtype": "SoftwareSourceCode",
      "keywords": ["GitHub Actions", "CI/CD", "Automated Testing", "Travis", "GitHub", "Kubernetes"]
    },
    {
      "level": "Senior",
      "name": "UI Components",
      "itemtype": "SoftwareSourceCode",
      "keywords": ["Web Components", "VueJS", "Lit", "Sass", "HandlebarsJS", "ReactJS", "AngularJS"]
    },
    {
      "level": "Senior",
      "name": "Soft Skills",
      "keywords": [
        "Agile",
        "honest and clear communicator",
        "Design Thinking",
        "developer advocacy",
        "developer translation"
      ]
    },
    {
      "level": "Senior",
      "name": "Libraries & Tools",
      "itemtype": "SoftwareSourceCode",
      "keywords": [
        "NodeJS ",
        "Vite",
        "Storybook",
        "LangChain AI",
        "Docker",
        "GraphQL",
        "ExpressJS",
        "Octokit",
        "Wordpress",
        "i18n",
        "Microdata"
      ]
    }
  ],
  "volunteer": [
    {
      "startDate": "2000-01-01",
      "endDate": "2001-01-01",
      "position": "Volunteer Person",
      "summary": "This is an entry for volunteer so I have data to test with.",
      "url": "https://www.eff.org/",
      "organization": "The helping place",
      "highlights": ["A very important and helpful thing", "Much help, so volunting"]
    },
    {
      "startDate": "2021-01-01",
      "endDate": "2022-01-01",
      "position": "Volunteer Person",
      "summary": "This is a 2nd entry for volunteer so I have data to test with.",
      "url": "https://runforsomething.net/",
      "organization": "The giving place",
      "highlights": ["A very important thing given", "Much give, so volunting"]
    }
  ],
  "projects": [
    {
      "startDate": "2023-04-01",
      "name": "StoryDocker",
      "url": "https://github.com/storydocker",
      "description": "Storybook, but as a microservice",
      "Type": "open source",
      "roles": ["Architect", "Owner"],
      "highlights": [
        "Implemented Storybook as a microservice using Docker Containers released as an open-source tool (StockDocker) able to be installed with zero dependencies and which features a full testing suite enabling prototyping and testing UI and user experience via Storybook’s testing-library integrations.",
        "Eliminated the need for multiple implementations of Storybook (previously one for each application development environment) by introducing the ability for Storybook to run multiple JS frameworks out-of-the-box."
      ]
    },
    {
      "startDate": "2012-01-01",
      "entity": "videogame.camp",
      "name": "The Chase",
      "endDate": "2014-01-01",
      "keywords": ["raspberry pi", "linux"],
      "url": "https://videogame.camp/the-chase/about/",
      "description": "A high-tech game of hide and seek",
      "Type": "meatspace",
      "roles": ["Inventor", "Developer"],
      "highlights": [
        "Created a raspberry pi-based remote camera live projection system",
        "Hosted multiple in-person events where the public had to look for the ghost in the crowd"
      ]
    },
    {
      "startDate": "2023-08-01",
      "name": "Profile Components",
      "keywords": ["web components", "native browser APIs", "evergreen"],
      "url": "https://github.com/scottnath/profile-components",
      "description": "zero dependency native web components to present user profiles",
      "Type": "open source",
      "roles": ["Architect", "Developer"],
      "highlights": [
        "Created native web components to learn web components",
        "Created a set of zero dependency native web components to present user profiles from various social networks by querying the site APIs for the latest user profile",
        "Styling to web standards and cross-browser compatibility using the newest browser-supported CSS functionality like nesting and container-queries",
        "Architected fullstack DevOps solutions to ensure overall quality of the project including a Storybook implementation with user interface design testing and VRT (visual regression testing), CI/CD for automated deployment, releases, and testing, and auto-generated PRs for dependency updates",
        "Test driven development using the native Node test runner, node:test, Guidepup for screen reader and web accessibility assurance."
      ]
    },
    {
      "startDate": "2014-01-01",
      "name": "Pattern Library",
      "endDate": "2016-01-01",
      "url": "https://github.com/pattern-library",
      "description": "A system-agnostic HTML pattern library",
      "Type": "open source",
      "roles": ["Architect", "Developer"],
      "highlights": [
        "A Node.js storage-and-sharing solution for functioning UX patterns.",
        "My first component library development system",
        "Already into cross-framework in 2015!",
        "Allowed usage of html/css/javascript across multiple systems and includes tools for *design-in-browser* methodologies."
      ]
    },
    {
      "startDate": "2016-01-01",
      "name": "Punchcard CMS",
      "endDate": "2018-12-31",
      "url": "https://github.com/punchcard-cms",
      "description": "Headless Content Management System designed with content strategy at its heart. Built with Node.",
      "Type": "open source",
      "roles": ["Architect", "Developer"],
      "highlights": [
        "Designed and developed a server-side headless, open-source content management system built with a focus on quality through content-strategy reflecting real-world use cases and a lean Postgresql/postgres backend.",
        "Architected full stack system architecture for auto-generated forms, localization, role-based administration, content approval workflows with revisioning, scheduled releases, caching, and subscriptions via webhooks."
      ]
    }
  ],
  "languages": [
    {
      "language": "English",
